Add model.go to make package model lookable
darshkpatel/NetNetra pull request #20
Opened 2019-12-21 07:22 UTC by invinciblycool

2019-12-21 14:22 UTC, agarwalarjun123 commented
Update these files

 https://github.com/darshkpatel/NetNetra/blob/dee7b5dd9aa706cda77f714ebe14c934b68bb24a/packetDeserializer.go#L25

https://github.com/darshkpatel/NetNetra/blob/dee7b5dd9aa706cda77f714ebe14c934b68bb24a/model/schema.go#L26

2019-12-21 14:27 UTC, agarwalarjun123 requested changes
have a look at this https://github.com/darshkpatel/NetNetra/pull/20#issuecomment-568184527

2019-12-22 03:57 UTC, darshkpatel approved these changes

2019-12-23 06:58 UTC, invinciblycool commented
@agarwalarjun123 @darshkpatel Indexing DNS data did not seem useful(atleast now).

Please check.

2019-12-23 07:49 UTC, agarwalarjun123 approved these changes

2019-12-23 07:49 UTC, merged